apply plugin: 'com.android.application'\n\nandroid {\n    compileSdkVersion 30\n    defaultConfig {\n        applicationId "com.netping"\n        minSdkVersion 21\n        targetSdkVersion 30\n        versionCode 1\n        versionName "1.0"\n    }\n    buildTypes {\n        release {\n            minifyEnabled false\n            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'\n        }\n    }\n}\n\ndependencies {\n    implementation 'com.android.support:appcompat-v7:30.0.0'\n    implementation 'com.android.support.constraint:constraint-layout:2.0.4'\n    implementation 'com.google.android.gms:play-services-location:17.0.0'\n    implementation 'com.google.android.gms:play-services-maps:17.0.0'\n    testImplementation 'junit:junit:4.12'\n}